const REPOSITORY='cookiescakes/cookiescakeswebpage';
const GITHUB_API='https://api.github.com';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, X-Menu-Publish-Password','Access-Control-Allow-Methods':'POST, OPTIONS'};

function response(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json',...corsHeaders}});}
function isSafeImagePath(path){return /^images\/[a-z0-9][a-z0-9._-]*$/i.test(path);}
async function github(env,path,init={}){const result=await fetch(`${GITHUB_API}/repos/${REPOSITORY}${path}`,{...init,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${env.GITHUB_TOKEN}`,...init.headers}});if(!result.ok){const detail=await result.text();throw new Error(`GitHub ${result.status}: ${detail.slice(0,300)}`);}return result.json();}
async function createBlob(env,content,encoding='base64'){const result=await github(env,'/git/blobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,encoding})});return result.sha;}

export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname!=='/api/publish-menu')return env.ASSETS.fetch(request);if(request.method==='OPTIONS')return new Response(null,{headers:corsHeaders});if(request.method!=='POST')return response({error:'Method not allowed'},405);if(!env.GITHUB_TOKEN||!env.MENU_PUBLISH_PASSWORD)return response({error:'Publishing is not configured yet.'},503);if(request.headers.get('X-Menu-Publish-Password')!==env.MENU_PUBLISH_PASSWORD)return response({error:'Incorrect publish password.'},401);try{const payload=await request.json();if(typeof payload.menuData!=='string'||payload.menuData.length>500000)return response({error:'Invalid menu data.'},400);const images=Array.isArray(payload.images)?payload.images:[];if(images.length>30)return response({error:'Too many images in one publish.'},400);for(const image of images){if(!isSafeImagePath(image.path)||typeof image.content!=='string'||image.content.length>14000000)return response({error:'One of the images is invalid or too large.'},400);}const head=await github(env,'/git/ref/heads/main');const parent=await github(env,`/git/commits/${head.object.sha}`);const treeEntries=[];treeEntries.push({path:'dist/menu-data.js',mode:'100644',type:'blob',sha:await createBlob(env,btoa(unescape(encodeURIComponent(payload.menuData))))});for(const image of images){treeEntries.push({path:`dist/${image.path}`,mode:'100644',type:'blob',sha:await createBlob(env,image.content)});}const tree=await github(env,'/git/trees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base_tree:parent.tree.sha,tree:treeEntries})});const commit=await github(env,'/git/commits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update weekly menu from Cookies Cakes manager',tree:tree.sha,parents:[head.object.sha]})});await github(env,'/git/refs/heads/main',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:commit.sha,force:false})});return response({ok:true,commit:commit.sha});}catch(error){console.error(error);const conflict=String(error.message).includes('GitHub 422');return response({error:conflict?'The repository changed. Reload the manager and try again.':'Publishing failed. Check the Worker secrets and try again.'},conflict?409:500);}}};
